//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Collection.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://reemsonline.com/getnewdate.asmx")]
        public string Collections_Reemsonline_GetNewDate {
            get {
                return ((string)(this["Collections_Reemsonline_GetNewDate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=FEMMY\\SQLEXPRESS;Initial Catalog=CENAbeokuta;Persist Security Info=Tr" +
            "ue;User ID=sa;Password=1964")]
        public string TaxSmartSuiteConnectionString {
            get {
                return ((string)(this["TaxSmartSuiteConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/oyo/ReceiptService.asmx")]
        public string Collections_TestReceiptServices_ReceiptService {
            get {
                return ((string)(this["Collections_TestReceiptServices_ReceiptService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.reemsonline.com/servicesinternal/receiptservice.asmx")]
        public string Collections_Kogireceiptservice_ReceiptService {
            get {
                return ((string)(this["Collections_Kogireceiptservice_ReceiptService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://74.208.222.200/state_akwaibom/receiptservice.asmx")]
        public string Collections_AkwaIbomReceiptServices_ReceiptService {
            get {
                return ((string)(this["Collections_AkwaIbomReceiptServices_ReceiptService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.reemsonline.com/SMS/processSms.asmx")]
        public string Collections_processSms_ProcessSms {
            get {
                return ((string)(this["Collections_processSms_ProcessSms"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.ogunstaterevenue.com/OGS_IPS/ReceiptService.asmx")]
        public string Collections_ReceiptServices_ReceiptService {
            get {
                return ((string)(this["Collections_ReceiptServices_ReceiptService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://oyostatebir.com/OYI_IPS/ReceiptService.asmx")]
        public string Collections_OyoReceiptServices_ReceiptService {
            get {
                return ((string)(this["Collections_OyoReceiptServices_ReceiptService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://deltabir.com/DSI_IPS/receiptservice.asmx")]
        public string Collections_DeltaBir_ReceiptService {
            get {
                return ((string)(this["Collections_DeltaBir_ReceiptService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=FEMMY;Initial Catalog=TaxSmartSuiteRevisedNew10032017;User ID=sa;Pass" +
            "word=1975")]
        public string TaxSmartSuiteRevisedConnectionString {
            get {
                return ((string)(this["TaxSmartSuiteRevisedConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=FEMSY;Initial Catalog=TaxSmartSuiteRevisedNewOG14022017;User ID=sa;Pa" +
            "ssword=1975")]
        public string TaxSmartSuiteRevisedNewOG14022017ConnectionString {
            get {
                return ((string)(this["TaxSmartSuiteRevisedNewOG14022017ConnectionString"]));
            }
        }
    }
}
