//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankStatementExcel.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BankStatementExcel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;windows-1252&quot;?&gt;
        ///&lt;BankDirectory&gt;
        ///  &lt;Bank&gt;
        ///    &lt;Name&gt;Abigi Microfinance Bank&lt;/Name&gt;
        ///    &lt;Code&gt;ABMFB&lt;/Code&gt;
        ///  &lt;/Bank&gt;
        ///  &lt;Bank&gt;
        ///    &lt;Name&gt;Access Bank Nigeria Plc&lt;/Name&gt;
        ///    &lt;Code&gt;Abp&lt;/Code&gt;
        ///  &lt;/Bank&gt;
        ///  &lt;Bank&gt;
        ///    &lt;Name&gt;Afribank Plc&lt;/Name&gt;
        ///    &lt;Code&gt;Afb&lt;/Code&gt;
        ///  &lt;/Bank&gt;
        ///  &lt;Bank&gt;
        ///    &lt;Name&gt;Astra Polaris Microfinance Bank&lt;/Name&gt;
        ///    &lt;Code&gt;AMFB&lt;/Code&gt;
        ///  &lt;/Bank&gt;
        ///  &lt;Bank&gt;
        ///    &lt;Name&gt;BOND BANK&lt;/Name&gt;
        ///    &lt;Code&gt;BOND&lt;/Code&gt;
        ///  &lt;/Bank&gt;
        ///  &lt;Bank&gt;
        ///    &lt;Name&gt;BOROMU MICROFINA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BankTest {
            get {
                return ResourceManager.GetString("BankTest", resourceCulture);
            }
        }
    }
}
