//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankReconciliation.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.reemsonline.com/serverreems.asmx")]
        public string BankReconciliation_ReceiptCollection_SERVERREEMS {
            get {
                return ((string)(this["BankReconciliation_ReceiptCollection_SERVERREEMS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.ogunstaterevenue.com/OGS_IPS/ReceiptService.asmx")]
        public string BankReconciliation_Collections_ReceiptService {
            get {
                return ((string)(this["BankReconciliation_Collections_ReceiptService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.reemsonline.com/interswitch/reems.asmx")]
        public string BankReconciliation_ReconciliationUpload_REEMS {
            get {
                return ((string)(this["BankReconciliation_ReconciliationUpload_REEMS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.reemsonline.com/DSI_IPS/collectionmanager.asmx")]
        public string BankReconciliation_CentralDetla_CollectionManager {
            get {
                return ((string)(this["BankReconciliation_CentralDetla_CollectionManager"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.reemsonline.com/OYI_IPS/collectionmanager.asmx")]
        public string BankReconciliation_Centraloyo_CollectionManager {
            get {
                return ((string)(this["BankReconciliation_Centraloyo_CollectionManager"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.reemsonline.com/state_akwaibom/collectionmanager.asmx")]
        public string BankReconciliation_CentralAkwa_CollectionManager {
            get {
                return ((string)(this["BankReconciliation_CentralAkwa_CollectionManager"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://74.208.222.197/OYI_IPS/collectionmanager.asmx")]
        public string BankReconciliation_StateOyo_CollectionManager {
            get {
                return ((string)(this["BankReconciliation_StateOyo_CollectionManager"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://74.208.222.200/state_akwaibom/collectionmanager.asmx")]
        public string BankReconciliation_StateAkwa_CollectionManager {
            get {
                return ((string)(this["BankReconciliation_StateAkwa_CollectionManager"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.deltabir.com/DSI_IPS/collectionmanager.asmx")]
        public string BankReconciliation_StateDelta_CollectionManager {
            get {
                return ((string)(this["BankReconciliation_StateDelta_CollectionManager"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.ogunstaterevenue.com/OGS_IPS/CollectionManager.asmx")]
        public string BankReconciliation_StateOgun_CollectionManager {
            get {
                return ((string)(this["BankReconciliation_StateOgun_CollectionManager"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.reemsonline.com/SMS/processSms.asmx")]
        public string BankReconciliation_ProcessSms_ProcessSms {
            get {
                return ((string)(this["BankReconciliation_ProcessSms_ProcessSms"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.reemsonline.com/OGS_IPS/collectionmanager.asmx")]
        public string BankReconciliation_Centralogun_CollectionManager {
            get {
                return ((string)(this["BankReconciliation_Centralogun_CollectionManager"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=FEMSY;Initial Catalog=TaxSmartSuiteRevisedNewDelta18072016;Persist Se" +
            "curity Info=True;User ID=sa;Password=1975")]
        public string TaxSmartSuiteRevised_oyoConnectionString {
            get {
                return ((string)(this["TaxSmartSuiteRevised_oyoConnectionString"]));
            }
        }
    }
}
